apiVersion: v1
kind: Service
metadata:
  name: pythonhttpserverconfig-service
spec:
  selector:
    app: pythonhttpserverconfig
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
