apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pythonhttpserverconfigs.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: pythonhttpserverconfigs
    singular: pythonhttpserverconfig
    kind: PythonHTTPServerConfig
    shortNames:
    - pyhttp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 100
              default: 1
            port:
              type: integer
              minimum: 1
              maximum: 65535
              default: 80
            ports:
              type: array
              items:
                type: object
                required:
                - name
                - port
                properties:
                  name:
                    type: string
                    minLength: 1
                    maxLength: 15
                  port:
                    type: integer
                    minimum: 1
                    maximum: 65535
            host:
              type: string
              pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
              minLength: 1
              maxLength: 63
